# INput Data and Train Data Shape

In [21]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import SimpleRNN, GRU, LSTM, Bidirectional

In [27]:
train_X = [[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]
print(np.shape(train_X))

(4, 5)


In [29]:
train_X = np.reshape(train_X, (-1, 4, 5))
print(np.shape(train_X))

(1, 4, 5)


# SimpleRNN and Hidden states

In [30]:
rnn = SimpleRNN(3)
# rnn = SimpleRNN(3, return_sequences=False, return_state=false)  와 동일

hidden_state = rnn(train_X)

print('hidden state :{}, shape : {}'.format(hidden_state, hidden_state.shape))

hidden state :[[-0.9907969   0.9706209  -0.99491644]], shape : (1, 3)


In [31]:
rnn = SimpleRNN(3, return_sequences=True)
hidden_states = rnn(train_X)

print('hidden states :{}, shape : {}'.format(hidden_states, hidden_states.shape))

hidden states :[[[-0.99398255  0.99645585 -0.9985824 ]
  [-0.91670173  0.9079279  -0.99392253]
  [-0.7953156  -0.49624082 -0.9837846 ]
  [-0.96194243  0.77281255 -0.99808496]]], shape : (1, 4, 3)


# SimpleRNN and Return Sequence

In [32]:
rnn = SimpleRNN(3, return_sequences=True, return_state=True)
hidden_state, last_state = rnn(train_X)

print('hidden states :{}, shape : {}'.format(hidden_states, hidden_states.shape))
print('last hidden state :{}, shape : {}'.format(last_state, last_state.shape))

hidden states :[[[-0.99398255  0.99645585 -0.9985824 ]
  [-0.91670173  0.9079279  -0.99392253]
  [-0.7953156  -0.49624082 -0.9837846 ]
  [-0.96194243  0.77281255 -0.99808496]]], shape : (1, 4, 3)
last hidden state :[[-0.8261083  -0.92994195 -0.9950739 ]], shape : (1, 3)


# SimpleRNN and Return_Sequence

In [33]:
rnn = SimpleRNN(3, return_sequences=False, return_state=True)
hidden_state, last_state = rnn(train_X)

print('hidden state :{}, shape : {}'.format(hidden_state, hidden_state.shape))
print('last hidden state :{}, shape : {}'.format(last_state, last_state.shape))

hidden state :[[-0.9671581   0.13457406 -0.98929363]], shape : (1, 3)
last hidden state :[[-0.9671581   0.13457406 -0.98929363]], shape : (1, 3)
